version: 2
jobs:
   build:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - run: cd server && npm install
       - run: cd server && CI=true npm run build
   test:
     docker:
       - image: circleci/node:node:latest
     steps:
       - checkout
       - run: cd server && npm install
       - run: cd server && npm run test
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test