version: 2
jobs:
  build:
    working_directory: ~/server
    docker:
      image: circleci/node:latest
    steps:
      - checkout
      - run:
        working_directory: ~/server 
        command: npm install
      - run:
        working_directory: ~/server 
        command: CI=true npm run build
  test:
    docker:
      image: circleci/node:node:latest
    steps:
      - checkout
      - run:
        working_directory: ~/server 
        command: npm install
      - run:
        working_directory: ~/server 
        command: npm run test
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test